clean-source/plataforma/AplicacionOperaciones/Controllers/RecepcionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplicacionOperaciones.Controllers
{
    public class RecepcionController : Controller
    {
        ServicioAuth.ServicioAuthClient svcAuth = new ServicioAuth.ServicioAuthClient();
        ServicioCorreo.ServicioCorreoClient svcCorreo = new ServicioCorreo.ServicioCorreoClient();
        ServicioOperaciones.ServicioOperacionesClient svcOperaciones = new ServicioOperaciones.ServicioOperacionesClient();

        string tokenAuth = "Base U2VydmljaW8uQXV0aEBTZXJ2aWNpby5BdXRo";
        string agenteAplication = "AGENT_WEBSERVICE_APP";

        public ActionResult Index()
        {
            if (AplicationActive())
            {
                ViewBag.EnlaceRecepcion = ModuleControlRetornoPath() + "/Recepcion/Recepcionar";
            }
            else
            {
                return Redirect(ModuleControlRetornoPath() + "/Auth");
            }
            
            return View();
        }

        public ActionResult Recepcionar()
        {
            if (AplicationActive())
            {
                ViewBag.ReferenciaMessageRecepcion = "";
            }
            else
            {
                return Redirect(ModuleControlRetornoPath() + "/Auth");
            }

            return View();
        }

        public ActionResult Pagar()
        {
            if (AplicationActive())
            {
                ViewBag.ReferenciaMessagePagar = "";
                ViewBag.ReferenciaChequeIngresado = "";
                ViewBag.ReferenciaFiniquitoIngresado = "";
            }
            else
            {
                return Redirect(ModuleControlRetornoPath() + "/Auth");
            }

            return View();
        }

        public ActionResult Notariar()
        {
            if (AplicationActive())
            {
                ViewBag.ReferenciaMessageNotariar = "";
            }
            else
            {
                return Redirect(ModuleControlRetornoPath() + "/Auth");
            }

            return View();
        }

        #region "HTTPPOST"

        [HttpPost]
        public ActionResult AperturarBox(string codigoDespacho)
        {
            string view = string.Empty;

            try
            {
                ViewBag.ReferenciaDespachado = ModuleDespachoAperturado(codigoDespacho);

                switch (ViewBag.ReferenciaCodigoEvento)
                {
                    case "200":
                        view = "Recepcion/_BoxApertura";
                        break;
                    case "404":
                        view = "Recepcion/_BoxRecepcionar";
                        break;
                    case "300":
                        view = "Recepcion/_BoxEnd";
                        break;
                }

                
            }
            catch (Exception)
            {

            }

            return PartialView(view);
        }

        [HttpPost]
        public ActionResult Match(string codigo, string codigoCheque = "", string codigoFiniquito = "")
        {
            if (codigo.ToUpper().Contains("FNQ-"))
            {
                ViewBag.ReferenciaChequeIngresado = codigoCheque;
                ViewBag.ReferenciaFiniquitoIngresado = codigo;
                ViewBag.ReferenciaMessagePagar = "";
            }
            else if (codigo.ToUpper().Contains("CHQ-"))
            {
                ViewBag.ReferenciaChequeIngresado = codigo;
                ViewBag.ReferenciaFiniquitoIngresado = codigoFiniquito;
                ViewBag.ReferenciaMessagePagar = "";
            }
            else
            {
                ViewBag.ReferenciaChequeIngresado = codigoCheque;
                ViewBag.ReferenciaFiniquitoIngresado = codigoFiniquito;
                ViewBag.ReferenciaMessagePagar = "El codigo que esta leyendo es incosistente con el que permite el sistema, debe ser un finiquito o el cheque, favor leer un codigo de barra correcto";
            }

            return PartialView("Recepcion/_BoxPagar");
        }

        [HttpPost]
        public ActionResult PagarCheque(string codigoCheque, string codigoFiniquito)
        {
            string view = string.Empty;

            try
            {
                string[] paramMantFin = new string[21];
                string[] valMantFin = new string[21];
                DataSet dataMantencion;

                paramMantFin[0] = "@ACCION";
                paramMantFin[1] = "@USUARIOCREADOR";
                paramMantFin[2] = "@CODIGOFINIQUITO";
                paramMantFin[3] = "@METODOPAGO";
                paramMantFin[4] = "@CODIGOPAGO";
                paramMantFin[5] = "@CODIGOPROCESO";
                paramMantFin[6] = "@DESTINATARIO";
                paramMantFin[7] = "@BANCO";
                paramMantFin[8] = "@TIPOCUENTA";
                paramMantFin[9] = "@FECHA";
                paramMantFin[10] = "@NUMEROCUENTA";
                paramMantFin[11] = "@RUT";
                paramMantFin[12] = "@OBSERVACIONES";
                paramMantFin[13] = "@MONTO";
                paramMantFin[14] = "@VIGENTE";
                paramMantFin[15] = "@SECUENCIA";
                paramMantFin[16] = "@SERIECHQ";
                paramMantFin[17] = "@EMPRESAORIGEN";
                paramMantFin[18] = "@PAGINATION";
                paramMantFin[19] = "@TYPEFILTER";
                paramMantFin[20] = "@DATAFILTER";

                valMantFin[0] = "PAGFIN";
                valMantFin[1] = Session["base64Username"].ToString();
                valMantFin[2] = codigoFiniquito;
                valMantFin[3] = "";
                valMantFin[4] = "";
                valMantFin[5] = "";
                valMantFin[6] = "";
                valMantFin[7] = "";
                valMantFin[8] = "";
                valMantFin[9] = "";
                valMantFin[10] = "";
                valMantFin[11] = "";
                valMantFin[12] = "";
                valMantFin[13] = "";
                valMantFin[14] = "";
                valMantFin[15] = "";
                valMantFin[16] = codigoCheque;
                valMantFin[17] = "";
                valMantFin[18] = "";
                valMantFin[19] = "";
                valMantFin[20] = "";

                dataMantencion = svcOperaciones.CrudMantencionFiniquitos(paramMantFin, valMantFin).Table;

                foreach (DataRow rows in dataMantencion.Tables[0].Rows)
                {
                    switch (rows["Code"].ToString())
                    {
                        case "200":
                            view = "Recepcion/_BoxPagado";
                            ViewBag.ReferenciaChequeIngresado = "";
                            ViewBag.ReferenciaFiniquitoIngresado = "";
                            ViewBag.ReferenciaMessagePagado = rows["Message"].ToString();
                            break;
                        case "300":
                            view = "Recepcion/_BoxPagar";
                            ViewBag.ReferenciaChequeIngresado = "";
                            ViewBag.ReferenciaFiniquitoIngresado = "";
                            ViewBag.ReferenciaMessagePagar = rows["Message"].ToString();
                            break;
                    }
                    
                }

            }
            catch (Exception)
            {

            }

            return PartialView(view);
        }

        [HttpPost]
        public ActionResult NotariarFiniquito(string codigoFiniquito)
        {
            string view = string.Empty;
            try
            {
                string[] paramMantFin = new string[21];
                string[] valMantFin = new string[21];
                DataSet data;

                paramMantFin[0] = "@ACCION";
                paramMantFin[1] = "@USUARIOCREADOR";
                paramMantFin[2] = "@CODIGOFINIQUITO";
                paramMantFin[3] = "@METODOPAGO";
                paramMantFin[4] = "@CODIGOPAGO";
                paramMantFin[5] = "@CODIGOPROCESO";
                paramMantFin[6] = "@DESTINATARIO";
                paramMantFin[7] = "@BANCO";
                paramMantFin[8] = "@TIPOCUENTA";
                paramMantFin[9] = "@FECHA";
                paramMantFin[10] = "@NUMEROCUENTA";
                paramMantFin[11] = "@RUT";
                paramMantFin[12] = "@OBSERVACIONES";
                paramMantFin[13] = "@MONTO";
                paramMantFin[14] = "@VIGENTE";
                paramMantFin[15] = "@SECUENCIA";
                paramMantFin[16] = "@SERIECHQ";
                paramMantFin[17] = "@EMPRESAORIGEN";
                paramMantFin[18] = "@PAGINATION";
                paramMantFin[19] = "@TYPEFILTER";
                paramMantFin[20] = "@DATAFILTER";

                valMantFin[0] = "NOTFIN";
                valMantFin[1] = Session["base64Username"].ToString();
                valMantFin[2] = codigoFiniquito;
                valMantFin[3] = "";
                valMantFin[4] = "";
                valMantFin[5] = "";
                valMantFin[6] = "";
                valMantFin[7] = "";
                valMantFin[8] = "";
                valMantFin[9] = "";
                valMantFin[10] = "";
                valMantFin[11] = "";
                valMantFin[12] = "";
                valMantFin[13] = "";
                valMantFin[14] = "";
                valMantFin[15] = "";
                valMantFin[16] = "";
                valMantFin[17] = "";
                valMantFin[18] = "";
                valMantFin[19] = "";
                valMantFin[20] = "";

                data = svcOperaciones.CrudMantencionFiniquitos(paramMantFin, valMantFin).Table;

                foreach (DataRow rows in data.Tables[0].Rows)
                {
                    switch (rows["Code"].ToString())
                    {
                        case "200":

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxApertura.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @foreach (AplicacionOperaciones.Models.Recepcion.Recepcionar item in ViewBag.ReferenciaDespachado)
    {
        <img src="~/Resources/caja-abierta.png" class="ml-auto mr-auto dspl-inline-block" style="width: 70px;">
        <h1 class="family-teamwork" style="font-size: 20px;">Se ha aperturado el contenedor de codigo</h1>
        <h1 class="family-teamwork mt-10neg">@item.CodigoDespacho</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-2">
                <h1 class="family-teamwork color-428BCA fw-bold" style="font-size: 50px;">@item.Total</h1>
                <h3 class="family-teamwork mt-20neg" style="font-size: 20px;">Documentos totales</h3>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-2">
                <h1 class="family-teamwork color-9218492 fw-bold" style="font-size: 50px;">@item.Recepcionados</h1>
                <h3 class="family-teamwork mt-20neg" style="font-size: 20px;">Documentos Recepcionados</h3>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-2">
                <h1 class="family-teamwork fw-bold" style="font-size: 50px;">@item.Despachados</h1>
                <h3 class="family-teamwork mt-20neg" style="font-size: 20px;">Documentos Por Recepcionar</h3>
            </div>
            <div class="col-lg-3"></div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <h2 class="family-teamwork ta-center">Para recepcionar documentos debe hacer la lectura del codigo de barra de alguno de estos documentos</h2>
            </div>
        </div>
        <div class="row ta-center">
            <div class="col-lg-2"></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <img src="~/Resources/ilustracionlecturacheque.jpg" class="dspl-block m-auto" style="width: 150px;" />
                <h4 class="family-teamwork ta-center">Cheque Impreso</h4>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 150px;" />
                <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
            </div>
            <div class="col-lg-2"></div>
        </div>
    }
</div>

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxEnd.cshtml
@foreach (AplicacionOperaciones.Models.Recepcion.Recepcionar item in ViewBag.ReferenciaDespachado)
{
    <div class="row ta-center" style="width: 100%;">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @item.Message</h1>
            <img src="~/Resources/caja.png" class="ml-auto mr-auto dspl-inline-block" style="width: 70px;"/>
            <h1 class="family-teamwork" style="font-size: 20px;">Se ha recepcionado el contenedor de codigo</h1>
            <h1 class="family-teamwork mt-10neg">@item.CodigoDespacho</h1>
        </div>
    </div>
    <div class="row ta-center" style="width: 100%;">
        <div class="col-lg-3"></div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 class="family-teamwork color-428BCA fw-bold" style="font-size: 50px;">@item.Total</h1>
            <h3 class="family-teamwork mt-20neg" style="font-size: 20px;">Documentos totales Recepcionados</h3>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <h2 class="family-teamwork ta-center">Para abrir un nuevo contenedor debe leer el codigo de barra de alguno de estos documentos</h2>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                    <h4 class="family-teamwork ta-center">Comprobante de Despacho</h4>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                    <img src="~/Resources/ilustracionlecturacheque.jpg" class="dspl-block m-auto" style="width: 200px;" />
                    <h4 class="family-teamwork ta-center">Cheque Impreso</h4>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                    <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
                    <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
                </div>
            </div>
        </div>
    </div>
}

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxNotariado.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @if (ViewBag.ReferenciaMessageNotariar != "")
    {
        <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @ViewBag.ReferenciaMessageNotariar</h1>
    }
    <img src="~/Resources/ilustracionmatchchequedocumento.jpg" class="ml-auto mr-auto dspl-inline-block" style="width: 200px;">
    <h1 class="family-teamwork ta-center">¿Va a realizar el notariado de otro finiquito?</h1>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="family-teamwork ta-center">Para notariar debe leer el codigo de barra de este documento</h2>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
            <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
        </div>
    </div>
</div>

@using (Ajax.BeginForm("NotariarFiniquito", "Recepcion", new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "contentRecepcion",
    LoadingElementId = "loader"
}, new { @style = "position: absolute; top: 0; display: block; height: 100%; width: 100%; left: 0;" }))
{
    <input type="text" name="codigoFiniquito" id="codigoFiniquito" style="width: 100%; position: absolute; top: 0; left: 0; height: 100%; background-color: rgba(0, 0, 0, 0); color: rgba(0, 0, 0, 0);" autocomplete="off" />
    <input type="submit" value="ENVIAR" class="mt-100 dspl-block" style="z-index: 999999999999999; position: absolute;" />
}

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxNotariar.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @if (ViewBag.ReferenciaMessageNotariar != "")
    {
        <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/errorwarning.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @ViewBag.ReferenciaMessageNotariar</h1>
    }
    <img src="~/Resources/repartidor.png" class="ml-auto mr-auto dspl-inline-block" style="width: 70px;">
    <h1 class="family-teamwork ta-center">¿Va a realizar la notaria del finiquito?</h1>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="family-teamwork ta-center">Para notariar debe leer el codigo de barra de este documento</h2>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
            <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
        </div>
    </div>
</div>

@using (Ajax.BeginForm("NotariarFiniquito", "Recepcion", new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "contentRecepcion",
    LoadingElementId = "loader"
}, new { @style = "position: absolute; top: 0; display: block; height: 100%; width: 100%; left: 0;" }))
{
    <input type="text" name="codigoFiniquito" id="codigoFiniquito" style="width: 100%; position: absolute; top: 0; left: 0; height: 100%; background-color: rgba(0, 0, 0, 0); color: rgba(0, 0, 0, 0);" autocomplete="off" />
    <input type="submit" value="ENVIAR" class="mt-100 dspl-block" style="z-index: 999999999999999; position: absolute;" />
}

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxPagado.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @if (ViewBag.ReferenciaMessagePagado != "")
    {
        <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @ViewBag.ReferenciaMessagePagado</h1>
    }
    <img src="~/Resources/ilustracionmatchchequedocumento.jpg" class="ml-auto mr-auto dspl-inline-block" style="width: 200px;">
    <h1 class="family-teamwork ta-center">¿Va a realizar el pago de otro finiquito?</h1>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="family-teamwork ta-center">Para pagar debe leer el codigo de barra de estos documentos</h2>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">


    @using (Ajax.BeginForm("PagarCheque", "Recepcion", new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "contentRecepcion",
        LoadingElementId = "loader"
    }, new { @style = "width: 100%; display: block; position: absolute;" }))
    {
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <img src="~/Resources/ilustracionlecturacheque.jpg" class="dspl-block m-auto" style="width: 200px;" />
                <h4 class="family-teamwork ta-center">Cheque Impreso</h4>
                <div class="ta-center">
                    @if (ViewBag.ReferenciaChequeIngresado != "")
                    {
                        <input type="text" name="codigoCheque" class="dspl-none" value="@ViewBag.ReferenciaChequeIngresado" id="codigoCheque" />
                        <img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" />
                    }

                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
                <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
                <div class="ta-center">
                    @if (ViewBag.ReferenciaFiniquitoIngresado != "")
                    {
                        <input type="text" name="codigoFiniquito" class="dspl-none" value="@ViewBag.ReferenciaFiniquitoIngresado" id="codigoFiniquito" />
                        <img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" />
                    }

                </div>
            </div>
            <input type="submit" value="enviar2" class="dspl-none" id="btnMatch" />
        </div>
    }

</div>

@using (Ajax.BeginForm("Match", "Recepcion", new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "contentRecepcion",
    LoadingElementId = "loader",
    OnSuccess = "validaMatch"
}, new { @style = "position: absolute; top: 0; display: block; height: 100%; width: 100%; left: 0;" }))
{
    <input type="text" name="codigoFiniquito" value="@ViewBag.ReferenciaFiniquitoIngresado" />
    <input type="text" name="codigoCheque" value="@ViewBag.ReferenciaChequeIngresado" />
    <input type="text" name="codigo" id="codigoDespacho" style="width: 100%; position: absolute; top: 0; left: 0; height: 100%; background-color: rgba(0, 0, 0, 0); color: rgba(0, 0, 0, 0);" autocomplete="off" />
    <input type="submit" value="ENVIAR" class="mt-100 dspl-block" style="z-index: 999999999999999; position: absolute;" />
}

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxPagar.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @if (ViewBag.ReferenciaMessagePagar != "")
    {
        <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/errorwarning.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @ViewBag.ReferenciaMessagePagar</h1>
    }
    <img src="~/Resources/repartidor.png" class="ml-auto mr-auto dspl-inline-block" style="width: 70px;">
    <h1 class="family-teamwork ta-center">¿Va a realizar el pago del finiquito?</h1>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="family-teamwork ta-center">Para pagar debe leer el codigo de barra de estos documentos</h2>
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-12">


    @using (Ajax.BeginForm("PagarCheque", "Recepcion", new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "contentRecepcion",
        LoadingElementId = "loader"
    }, new { @style = "width: 100%; display: block; position: absolute;" }))
    {
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <img src="~/Resources/ilustracionlecturacheque.jpg" class="dspl-block m-auto" style="width: 200px;" />
                <h4 class="family-teamwork ta-center">Cheque Impreso</h4>
                <div class="ta-center">
                    @if (ViewBag.ReferenciaChequeIngresado != "")
                    {
                        <label class="family-teamwork dspl-inline-block ta-center">
                            Se ha detectado lectura de cheque 
                            <input type="text" name="codigoCheque" class="family-teamwork dspl-inline" style="border: none; background-color: rgba(0, 0, 0, 0);" value="@ViewBag.ReferenciaChequeIngresado" id="codigoCheque" />
                        </label>
                        <img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-block" style="width: 30px;" />
                    }
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
                <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
                <div class="ta-center">
                    @if (ViewBag.ReferenciaFiniquitoIngresado != "")
                    {
                        <label class="family-teamwork dspl-inline-block ta-center">
                            Se ha detectado lectura de finiquito 
                            <input type="text" name="codigoFiniquito" class="family-teamwork dspl-inline" style="border: none; background-color: rgba(0, 0, 0, 0);" value="@ViewBag.ReferenciaFiniquitoIngresado" id="codigoFiniquito" />
                        </label>
                        <img src="~/Resources/corregir.png" class="ml-auto mr-auto dspl-block" style="width: 30px;" />
                    }

                </div>
            </div>
            <input type="submit" value="enviar2" class="dspl-none" id="btnMatch" />
        </div>
    }

</div>

@using (Ajax.BeginForm("Match", "Recepcion", new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "contentRecepcion",
    LoadingElementId = "loader",
    OnSuccess = "validaMatch"
}, new { @style = "position: absolute; top: 0; display: block; height: 100%; width: 100%; left: 0;" }))
{
    <input type="text" name="codigoFiniquito" value="@ViewBag.ReferenciaFiniquitoIngresado" />
    <input type="text" name="codigoCheque" value="@ViewBag.ReferenciaChequeIngresado" />
    <input type="text" name="codigo" id="codigoDespacho" style="width: 100%; position: absolute; top: 0; left: 0; height: 100%; background-color: rgba(0, 0, 0, 0); color: rgba(0, 0, 0, 0);" autocomplete="off" />
    <input type="submit" value="ENVIAR" class="mt-100 dspl-block" style="z-index: 999999999999999; position: absolute;" />
}

clean-source/plataforma/AplicacionOperaciones/Views/Shared/Recepcion/_BoxRecepcionar.cshtml
<div class="col-12 col-sm-12 col-md-12 col-lg-12 ta-center">
    @if (ViewBag.ReferenciaMessageRecepcion != "")
    {
        <h1 class="family-teamwork" style="font-size: 20px;"><img src="~/Resources/errorwarning.png" class="ml-auto mr-auto dspl-inline-block" style="width: 30px;" /> @ViewBag.ReferenciaMessageRecepcion</h1>
    }
    <img src="~/Resources/caja.png" class="ml-auto mr-auto dspl-inline-block" style="width: 70px;">
    <h1 class="family-teamwork ta-center">¿Va a recepcionar el contenedor de despachado?</h1>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="family-teamwork ta-center">Para abrir el contenedor debe leer el codigo de barra de alguno de estos documentos</h2>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-4">
            <h4 class="family-teamwork ta-center">Comprobante de Despacho</h4>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-4">
            <img src="~/Resources/ilustracionlecturacheque.jpg" class="dspl-block m-auto" style="width: 200px;" />
            <h4 class="family-teamwork ta-center">Cheque Impreso</h4>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-4">
            <img src="~/Resources/ilustracionlecturadocumentos.jpg" class="dspl-block m-auto" style="width: 200px;" />
            <h4 class="family-teamwork ta-center">Finiquito o Caratula Finiquito</h4>
        </div>
    </div>
</div>